GET http://localhost:3001/api/persons/y45y4y45

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Gaze Rasterize",
    "number": "45731214564645",
    "userId": "61bdc4ef2a5c5d4dd4682a27"
}

###
DELETE http://localhost:3001/api/persons/60ac8d8380b69f37755974fc
content-type: application/json 

###
PUT http://localhost:3001/api/persons/60b06a5c4a631f3eb3f3e391
content-type: application/json 

{
    "name": "samplrefefrefrgegegvgnadsczcdcmee",
    "number": "4379r793fvvcdsgg79"
}

###
POST http://localhost:3001/api/users/ 
content-type: application/json

{
    "persons": [],
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}