GET http://localhost:3001/api/persons/y45y4y45

###
GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxYmRjNGVmMmE1YzVkNGRkNDY4MmEyNyIsImlhdCI6MTYzOTk4MDMxN30.P_X1kXwvWH6Kyz3EbLkRwY_kPE86m3R8imWUsPm2NFg

{
    "name": "Gaze RasterizeKumaris",
    "number": "41247641045"
}

###
DELETE http://localhost:3001/api/persons/61c01dba1be03c32a0caf59a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxYmRjNGVmMmE1YzVkNGRkNDY4MmEyNyIsImlhdCI6MTYzOTk4MDMxN30.P_X1kXwvWH6Kyz3EbLkRwY_kPE86m3R8imWUsPm2NFg

###
PUT http://localhost:3001/api/persons/61bdd3e83458205394d0a990
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxYmRjNGVmMmE1YzVkNGRkNDY4MmEyNyIsImlhdCI6MTYzOTk4MDMxN30.P_X1kXwvWH6Kyz3EbLkRwY_kPE86m3R8imWUsPm2NFg

{
    "name": "Checker",
    "number": "4379g5679"
}
