GET http://localhost:8001/api/persons/

###
GET http://localhost:8001/api/persons/info

###
GET http://localhost:8001/api/persons/check
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdpYW4iLCJpZCI6IjYxYzViN2ExM2RjOWYxNjg3ODM3YjBkYyIsImlhdCI6MTY0NjY0OTM3OH0.jxpPtItUE_gzU1R41vopRqtem0vAAexp-VHU3-_RGQs

###
POST http://localhost:8001/api/persons/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxYmRjNGVmMmE1YzVkNGRkNDY4MmEyNyIsImlhdCI6MTYzOTk4MDMxN30.P_X1kXwvWH6Kyz3EbLkRwY_kPE86m3R8imWUsPm2NFg

{
    "name": "Bion Sachdeva",
    "number": "4415646"
}

###
DELETE http://localhost:8001/api/persons/61bd82f2cce6333034831e32
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxYmRjNGVmMmE1YzVkNGRkNDY4MmEyNyIsImlhdCI6MTY0MDM0NzY0MX0.caYdKPYdAUxjtlrZ5yn3--Pc4VLo4D1oIWUd_HgZHWQ

###
PUT http://localhost:8001/api/persons/61bdd3e83458205394d0a990
content-type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxYmRjNGVmMmE1YzVkNGRkNDY4MmEyNyIsImlhdCI6MTYzOTk4MDMxN30.P_X1kXwvWH6Kyz3EbLkRwY_kPE86m3R8imWUsPm2NFg

{
    "name": "Checker",
    "number": "4379g5679"
}
